import { KeyboardEventHandler, useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";

import styles from "../styles/Home.module.css";

export default function Bot() {
  const [check, setCheck] = useState(true);
  const router = useRouter();

  useEffect(() => {
    if (localStorage.getItem("auth") !== "true") {
      router.push("/");
    }

    setCheck(false);
  }, []);

  const [value, setValue] = useState("");
  const [loading, setLoading] = useState(false);

  const handleClick = async () => {
    if (value.trim() === "") {
      return;
    }

    setLoading(true);

    await fetch("/api/message", {
      method: "POST",
      body: JSON.stringify({ value }),
    });

    setValue("");
    setLoading(false);
  };

  const handleKeyDown: KeyboardEventHandler<HTMLInputElement> = (event) => {
    if (event.key === "Enter") {
      handleClick();
    }
  };

  const handleChange = ({ target: { value } }: { target: { value: string } }) =>
    setValue(value);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>NGBOT</h1>
        {check ? (
          <div>Getting user...</div>
        ) : (
          <div className={styles.controlls}>
            <input
              placeholder="message"
              value={value}
              onChange={handleChange}
              className={styles.input}
              onKeyDown={handleKeyDown}
              disabled={loading}
            />
            <button
              onClick={handleClick}
              className={styles.button}
              disabled={loading}
            >
              {loading ? "..." : "Send"}
            </button>
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://t.me/SideswipeLoi"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by SideswipeLoi
        </a>
      </footer>
    </div>
  );
}
