import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://t.me/ng_lead_minsk_bot">NGBOT</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://t.me/SideswipeLoi"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by SideswipeLoi
        </a>
      </footer>
    </div>
  );
}
